apps/myUtils/urls.py
from django.urls import path
# from .views import Welcome
from .views import Error, Delete_data, Alert_stu_data, Download, GetClass, ShowNotification, GetColleges, AddStu, AddField, ImportDataToexcel, CreateTable, Search, ShareGetClass, CombinedExcel
app_name = 'myUtils'
urlpatterns = [
    path('', Error.as_view(), name='error'),
    path('/delete_stu_data', Delete_data.as_view(), name="delete_stu_data" ),
    path('/alter', Alert_stu_data.as_view(), name="alter"),
    path('/getClass', GetClass.as_view(), name="getClass"),
    path('/getcolleges', GetColleges.as_view(), name='getcolleges'),
    path('/addstu', AddStu.as_view(), name="addstu"),
    path('/addfield', AddField.as_view(), name="addfield"),
    path('/search', Search.as_view(), name='serch'),
    path('/sharegetclass', ShareGetClass.as_view(), name="sharegetclass"),
    path('/combined', CombinedExcel.as_view(), name="combined"),
    path('/import', ImportDataToexcel.as_view(), name='import'),
    path('/createtable', CreateTable.as_view(), name="createtable"),
    path('/shownotification', ShowNotification.as_view(), name="shownotification"),
    path('/download', Download.as_view(), name="download")

]

apps/stu_table/urls.py
from django.urls import path
from .views import Merge, Anomaly, Replenish, Message_edit, Stu_data_list, ShareLogin, ShareForm
app_name = 'stu_table'
urlpatterns = [
    path('merge', Merge.as_view(), name="merge"),
    path('anomaly', Anomaly.as_view(), name="anomaly" ),
    path('replenish', Replenish.as_view(), name="replenish"),
    path('edit', Message_edit.as_view(), name='edit'),
    path('data_list', Stu_data_list.as_view(), name="stu_data_list"),
    path('shareLogin', ShareLogin.as_view(), name="sharelogin"),
    path('shareform', ShareForm.as_view(), name="shareform"),
 
]

apps/user/urls.py
from django.urls import path
from .views import UserList, ChangePassword, AddUser, DeleteUser, PersonalDetails

app_name = 'user'
urlpatterns = [
    path('userlist', UserList.as_view(), name='userlist'),
    path('changepassword', ChangePassword.as_view(), name='changepassword'),
    path('adduser', AddUser.as_view(), name="adduser"),
    path('deleteuser', DeleteUser.as_view(), name='deleteuser'),
    path('personaldetails', PersonalDetails.as_view(), name="personaldetails")
]

intelligent_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static   # 新加入 
from django.conf import settings             # 新加入 
from .views import Index, Welcome, AdminManagement, RoleManagement, Permiclassify, PermiManagement, \
    Login, PermissionAdd, PermissionDelete, PermissionEdit, RoleDelete, RoleAdd, RoleEdit, LogOut, Register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name="login"),
    path('logout', LogOut.as_view(), name="logout"),
    path('register', Register.as_view(), name="register" ),
    path('index', Index.as_view(), name="index"),
    path('welcome', Welcome.as_view(), name="welcome"),
    path('manage/', include('stu_table.urls')),
    path('adminManagement/', AdminManagement.as_view(), name="management"),
    path('user/', include('user.urls')),
    path('role', RoleManagement.as_view(), name="rolemanagement"),
    path('roledelete', RoleDelete.as_view(), name="roledelete"),
    path('roleadd', RoleAdd.as_view(), name="roleadd"),
    path('roleedit', RoleEdit.as_view(), name='roleedit'),
    path('permiclassify', Permiclassify.as_view(), name='permiclassify'),
    path('permiManagement', PermiManagement.as_view(), name="permiManagement"),
    path('permissionadd', PermissionAdd.as_view(), name='permissionadd'),
    path('permissiondelete', PermissionDelete.as_view(), name='permissiondelete'),
    path('permissionedit', PermissionEdit.as_view(), name="permissionedit"),
    path('error', include('myUtils.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/html/adduser.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
<div class="content" style="width: 85%; margin-top:10px;">

<form class="layui-form" action="">
        <div class="layui-form-item">
          <label class="layui-form-label">用户名</label>
          <div class="layui-input-block">
            <input type="text" name="username" required  lay-verify="required" placeholder="请输入用户名" autocomplete="off" class="layui-input">
          </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">姓名</label>
            <div class="layui-input-block">
              <input type="text" name="name" required  lay-verify="required" placeholder="请输入姓名" autocomplete="off" class="layui-input">
            </div>
          </div>
        <div class="layui-form-item">
          <label class="layui-form-label">密码</label>
          <div class="layui-input-inline">
            <input type="password" name="password" required lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input password">
          </div>
          <div class="layui-form-mid layui-word-aux">密码长度6为以上</div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">确认密码</label>
            <div class="layui-input-inline">
              <input type="password" name="password" required lay-verify="required" placeholder="请确认密码" autocomplete="off" class="layui-input passwordAgain">
            </div>
            <div class="layui-form-mid layui-word-aux">密码长度6为以上</div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">身份</label>
          <div class="layui-input-block">
            <select name="user_role" lay-verify="required" lay-filter="user-role">
              <option value="" >请选择身份</option>
              {% for user_role in user_roles %}
                <option value="{{ user_role.role_name }}">{{ user_role.role_name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="layui-form-item college-select" style="display: none">
          <label class="layui-form-label">学院</label>
          <div class="layui-input-block">
            <select name="college" lay-verify="user-role" lay-filter="college">
              <option value="">请选择学院</option>
              {% for college in colleges %}
                <option value="{{ college.pk }}">{{ college.coolege_name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="layui-form-item class-select" style="display: none">
            <label class="layui-form-label">班级</label>
            <div class="layui-input-block">
              <select name="class" id="class_names" lay-verify="user-role" lay-filter="class">
                <option value="">请选择班级</option>
              </select>
            </div>
          </div>
        <div class="layui-form-item">
          <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
          </div>
        </div>
      </form>
</div>
    </body>
{% endblock %}
{% block script %}
    <script>
        //Demo
        layui.use('form', function(){
          var form = layui.form;
          form.on('select(user-role)', function(data){
            var dataValue = data.value;
            if(dataValue == "老师"){
              $('.college-select').show();
              $('.class-select').hide()
            }else if(dataValue == "班长"){
              $('.college-select').show();
              $('.class-select').show();
            }else if(dataValue == "管理员"){
              $('.college-select').hide();
              $('.class-select').hide();
            }
          });
          // 获取班级
          form.on('select(college)', function(data){
            var new_value = data.value;
            if (new_value != ""){
              $.ajax({
                    url: "{% url 'myUtils:getClass' %}",
                    type: "POST",
                    cache: false,
                    data: {'pk': new_value},
                    success: function(data){
                        var optionstring = "";
                        var meta = JSON.parse(data);
                        $.each(meta, function(i, item){
                            optionstring += '<option value="'+item.pk+'">'+item.fields.class_name+'</option>';
                        });
                        $("#class_names").html('<option value="">请选择班级</option>' + optionstring);
                        form.render('select');
                    },
                });   
            }
          })
          //监听提交
          form.on('submit(formDemo)', function(data){
            //  密码验证
            var password = $('.password').val();
            var passwordAgain = $('.passwordAgain').val();
            if (password.length >= 6 && passwordAgain.length >= 6){
              if (passwordAgain == password){
                $.post("{% url 'user:adduser' %}", data.field, function(data){
                  if(data.status == "success"){
                    var index = parent.layer.getFrameIndex(window.name);
                    //关闭当前frame
                    parent.layer.close(index);
                    parent.location.reload()
                  }else{
                    layer.msg(data.status,{icon: 5,time:1000, shift: 6},);
                  }

            }, 'json' );
              }else{
                layer.msg("两次密码不一致",{icon: 5,time:1000, shift: 6},);
              }
            }else{
              layer.msg("密码太短",{icon: 5,time:1000, shift: 6},);
            }
            // layer.msg(JSON.stringify(data.field));
            return false;
          });
        });
    </script>
{% endblock %}

templates/html/manyExcel.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 数据导入 {% endblock %}
{% block link %} <link rel="stylesheet" href="{% static 'stu_table/css/style.css' %}">{% endblock %}
{% block content %}
<body class="form-wrap">      
<div class=" layui-fluid  layui-bg-white">

<form action="" enctype="multipart/form-data">
  <input type="file" name="" multiple="true" id="">
</form>
<blockquote class="layui-elem-quote">为节省服务器开销，以下示例均未配置真实上传接口，所以每次上传都会报提示：请求上传接口出现异常，这属于正常现象。</blockquote>   
<div class="layui-upload">
  <button type="button" class="layui-btn layui-btn-normal" id="testList">选择多文件</button> 
  <div class="layui-upload-list">
    <table class="layui-table">
      <thead>
        <tr><th>文件名</th>
        <th>大小</th>
        <th>状态</th>
        <th>操作</th>
      </tr></thead>
      <tbody id="demoList"></tbody>
    </table>
  </div>
  <button type="button" class="layui-btn"  id="testListAction">开始上传</button>
</div> 
</div>
{% endblock %}       
<!-- <script type="text/javascript" src="../lib/layui/layui.js" charset="utf-8"></script> -->
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
{% block script %} 
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
layui.use('upload', function(){
  var $ = layui.jquery
  ,upload = layui.upload;
  
 
  
  //多文件列表示例
  var demoListView = $('#demoList')
  ,uploadListIns = upload.render({
    elem: '#testList'
    ,url: '{% url "myUtils:combined" %}'
    ,exts: 'xls|excel|xlsx'
    ,accept: 'file'
    ,multiple: true
    ,auto: false
    ,bindAction: '#testListAction'
    ,choose: function(obj){   
      var files = this.files = obj.pushFile(); //将每次选择的文件追加到文件队列
      //读取本地文件
      obj.preview(function(index, file, result){
        var tr = $(['<tr id="upload-'+ index +'">'
          ,'<td>'+ file.name +'</td>'
          ,'<td>'+ (file.size/1014).toFixed(1) +'kb</td>'
          ,'<td>等待上传</td>'
          ,'<td>'
            ,'<button class="layui-btn layui-btn-xs demo-reload layui-hide">重传</button>'
            ,'<button class="layui-btn layui-btn-xs layui-btn-danger demo-delete">删除</button>'
          ,'</td>'
        ,'</tr>'].join(''));
        
        //单个重传
        tr.find('.demo-reload').on('click', function(){
          obj.upload(index, file);
        });
        
        //删除
        tr.find('.demo-delete').on('click', function(){
          delete files[index]; //删除对应的文件
          tr.remove();
          uploadListIns.config.elem.next()[0].value = ''; //清空 input file 值，以免删除后出现同名文件不可选
        });
        demoListView.append(tr);
      });
    }
    ,done: function(res, index, upload){
    console.log(res)
      if(res.code == 0){ //上传成功
        var tr = demoListView.find('tr#upload-'+ index)
        ,tds = tr.children();
        tds.eq(2).html('<span style="color: #5FB878;">上传成功</span>');
        tds.eq(3).html(''); //清空操作
        return delete this.files[index]; //删除文件队列已经上传成功的文件
      }
      this.error(index, upload);
    }
    ,error: function(index, upload){
      var tr = demoListView.find('tr#upload-'+ index)
      ,tds = tr.children();
    }
  });
  
  //绑定原始文件域
  // upload.render({
  //   elem: '#test20'
  //   ,url: '/upload/'
    
  //   ,done: function(res){
  //     console.log(res)
  //   }
  });
  
// });
</script>
{% endblock %}

templates/html/stu-message-list.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
  <link rel="stylesheet" href="{% static 'stu_table/css/style.css' %}">
{% endblock %}
{% block content %}
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
      
        <a href="javascript:;" class="first_page">首页</a>
      </span>
      <a class="layui-btn layui-btn-primary layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:38px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so search-form">
          <div class="layui-input-inline">

              {% if role != "班长" %}
              <select name="choice_college" lay-filter="choice-college">
                  <option value="">请选择学院</option>
                  {% for college in colleges %}
                    <option value="{{ college.pk }}">{{ college }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="layui-input-inline">
                <select name="choice_class" class="choice-class" lay-filter="choice-class">
                  <option value="">请选择班级</option>
                  <!-- {% for college in colleges %}
                    <option value="{{ college.pk }}">{{ college }}</option>
                  {% endfor %} -->
                </select>
            {% endif %}
          </div>
          <div class="search-div">
            <input type="text" name="stu_name"  placeholder="请输入学生学号或姓名" autocomplete="off" class="layui-input search_input">
            <button class="layui-btn search" ><i class="layui-icon">&#xe615;</i></button>
          </div>
        </form>
      </div>
      <div class="about_data_list">
      </div>
    </div>
  </body>
  {% endblock %}
  {% block script %}
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });
      //  加载学生列表
      $(document).ready(function(){
        $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}");
      });
      // 点击分页 局部刷新
      function show_list(argument){
        $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}?page="+argument);
      }
       /*用户-停用*/
      function member_stop(obj,id){
          layer.confirm('确认要停用吗？',function(index){

              if($(obj).attr('title')=='启用'){
                //发异步把用户状态进行更改
                $(obj).attr('title','停用')
                $(obj).find('i').html('&#xe62f;');
                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!',{icon: 5,time:1000});

              }else{
                $(obj).attr('title','启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!',{icon: 5,time:1000});
              }
              
          });
      }

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              $.ajax({
                 url:  "{% url 'myUtils:delete_stu_data' %}",
                 type: 'POST',
                 data: {'data': id},
                 cache: false,
                 success: function(data){
                  layer.msg('删除成功', {icon: 1});
                   //发异步删除数据
                  var count =  $('.count').text()
                  $('.count').text(count-1)
                  $(obj).parents("tr").remove();
                  layer.msg('已删除!',{icon:1,time:1000});
                 },
                 error: function(xhr){
                  layer.msg('删除失败', {icon: 5});
                 },

              });
             
          });
      }
      // function x_admin_show(argument){
      //   alert('hello');
      // }
      // 删除
      function delAll (argument) {

        var data = tableCheck.getData();
        layer.confirm('确认要删除吗？'+data,function(index){
          $.ajax({
          url: "{% url 'myUtils:delete_stu_data' %}",
          type: "POST",
          data: {"data": JSON.stringify(data)},
          cache: false,
          success: function(data){
            // var a = $('.num').text();
            // $('.num').text(a - data['count']);
            layer.msg('删除成功', {icon: 1});
            var count =  $('.count').text()
            $('.count').text(count-data['count'])
            $(".layui-form-checked").not('.header').parents('tr').remove();
          },
          error: function(xhr){
            layer.msg('删除失败', {icon: 5});
          }
        });
        });
      }
      // 查询
      $('.search').click(function(){
        //  ajax 提交数据
                var value = $('.search_input').val()
                $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}?stu="+value);
        return false;
      })
      // 二级联动选择\学院 刷新班级
      layui.use('form', function(){
        var form = layui.form; 
        form.render('select');
        form.on('select(choice-college)', function(data){
            var new_value = data.value;
            if (new_value != ""){
                // ajax提交请求
                $.ajax({
                    url: "{% url 'myUtils:getClass' %}",
                    type: "POST",
                    cache: false,
                    data: {'pk': new_value},
                    success: function(data){
                        var optionstring = "";
                        var meta = JSON.parse(data);
                        $.each(meta, function(i, item){
                            optionstring += '<option value="'+item.pk+'">'+item.fields.class_name+'</option>';
                        });
                        $(".choice-class").html('<option value="" selected></option>' + optionstring);
                        form.render('select');
                        var value = $('.search-form').serialize()
                        $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}", value);
                    },
                });   
            }
        });
      });
    // 选择班级刷新页面
    layui.use('form', function(){
        var form = layui.form; 
        form.on('select(choice-class)', function(data){
              var value = $('.search-form').serialize()
              $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}", value);
            });
    });
    // 返回列表首页
    $('.first_page').click(function(){
      $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}");
    });
      
    </script>
 {% endblock %}

templates/html/upload1.html
{% extends 'base.html' %}
{% block content %}
  <body class="form-wrap">
            
  <div class=" layui-fluid  layui-bg-white">
  <blockquote class="layui-elem-quote">为节省服务器开销，服务器并不会保留您的文件</blockquote>   
            
  
  <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
    <legend>选完文件后不自动上传</legend>
  </fieldset>
  
  <div class="layui-upload">
    <button type="button" class="layui-btn layui-btn-normal" id="test8">选择文件</button>
    <button type="button" class="layui-btn" id="test9">开始上传</button>
  </div>

</body>
{% endblock %}
{% block script %}
          
<!-- <script type="text/javascript" src="../lib/layui/layui.js" charset="utf-8"></script> -->
<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
  
  //选完文件后不自动上传
  upload.render({
    elem: '#test8'
    ,url: '{% url "stu_table:merge" %}' //上传数据的请求url
    ,auto: false
    ,accept: 'file'
    ,exts: 'xls|excel|xlsx'
    //,multiple: true
    ,bindAction: '#test9'
    ,done: function(res){
      if (res['static'] == "error"){
        layui.use('layer', function(){
          var layer = layui.layer;
          
          layer.msg('出现错误');
        });  
      }else if(res['static'] == "success"){
        for(var i = 0; i<res['data_list'].length; i++){
          arrvalue=res['data_list'][i];//数组的索引是从0开始的
          console.log(arrvalue);//把取出的值打印在控制台上
        }
      }
      console.log(res)
    }
  });
</script>
{% endblock %}

templates/html/user-list.html
{% extends 'base.html' %}
{% block title%} 管理员管理 {% endblock %}
{% block content %}
  <body>
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="{% url 'user:userlist' %}">首页</a>
      <a class="layui-btn layui-btn-primary layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:38px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so" action="{% url 'user:userlist' %}" method="POST">
          <input type="text" name="username"  placeholder="请输入用户名" autocomplete="off" class="layui-input">
          <button class="layui-btn" type="submit"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
      </div>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" onclick="x_admin_show('添加用户','/user/adduser', 600, 400)"><i class="layui-icon"></i>添加</button>
        <span class="x-right" style="line-height:40px">共有数据：<span>{{ count }}</span>  条</span>
      </xblock>
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>ID</th>
            <th>登录名</th>
            <th>姓名</th>
            <th>手机</th>
            <th>邮箱</th>
            <th>角色</th>
            <th>操作</th>
        </thead>
        <tbody>
          {% for user in user_list %}
          <tr>
              <td>
                <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='{{ user.pk }}'><i class="layui-icon">&#xe605;</i></div>
              </td>
              <td>{{ user.pk }}</td>
              <td>{{ user.username }}</td>
              <td>{{ user.name }}</td>
              <td>{{ user.phone }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.user_role.role_name }}</td>
              <td class="td-manage">
                  <a  class="layui-btn layui-btn-sm layui-btn-warm" onclick="x_admin_show('修改密码','/user/changepassword?pk={{ user.pk }}',600,400)" title="修改密码" href="javascript:;">
                    修改密码
                  </a>
                  <a title="删除" class="layui-btn layui-btn-sm layui-btn-danger" onclick="member_del(this,'{{ user.pk }}')" href="javascript:;">
                    删除
                  </a>
                </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="page">
          <div>
              {% if user_list.has_previous %}
                <a class="prev" href="?page={{user_list.prevoius_page_number }}">&lt;&lt;</a>
              {% endif %}
              {% for page_num in user_list.paginator.page_range %}
                {% if page_num == user_list.number %}
                <span class="current">{{ page_num }}</span>
                {% else %}
                <!-- <a class="num" href="?page={{ page_num }}">{{ page_num }}</a> -->
                <a class="num" href="?page={{page_num}}">{{ page_num }}</a>
                {% endif %}
              {% endfor %}
              {% if user_list.has_next%}
                <a class="next" href="?page={{ user_list.next_page_number }}">&gt;&gt;</a>
              {% endif %}
            </div>
      </div>

    </div>
  </body>
  {% endblock %}
  {% block script %}
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });

       /*用户-停用*/
      function member_stop(obj,id){
          layer.confirm('确认要停用吗？',function(index){

              if($(obj).attr('title')=='启用'){

                //发异步把用户状态进行更改
                $(obj).attr('title','停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!',{icon: 5,time:1000});

              }else{
                $(obj).attr('title','启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!',{icon: 5,time:1000});
              }
              
          });
      }

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
            $.post("{% url 'user:deleteuser' %}", {'value': id}, function(data){
                var count = $('.count').text();
                  $('.count').text(count-1);
              })
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:1000});
          });
      }
      function delAll (argument) {
        var data = tableCheck.getData();
        if(data == ""){
            layer.msg('没有选中', {icon: 5});
          }else{
            layer.confirm('确认要删除吗？'+data,function(index){
              $.post("{% url 'user:deleteuser' %}", {'values': JSON.stringify(data)}, function(data){
                var count = $('.count').text();
                  $('.count').text(count-data['count']);
              })  
                //捉到所有被选中的，发异步进行删除
                layer.msg('删除成功', {icon: 1});
                $(".layui-form-checked").not('.header').parents('tr').remove();
            });
          }
      }
    </script>
  {% endblock %}

templates/html/welcome.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>欢迎页面</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="{% static 'css/font.css' %}">
        <link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    </head>
    <body>
    <div class="x-body layui-anim layui-anim-up">
        <blockquote class="layui-elem-quote">欢迎
            <span class="x-red">{{ request.user }}</span>&nbsp;&nbsp; 身份: &nbsp;<span class="x-red">{{ request.user.user_role }}</span>&nbsp;&nbsp; 上次登录时间: {{ user.last_login }}</blockquote>
        <div class="notification" style="width:300px; float: right; margin-top:5%;">
            {% for data in notification %}
            <div class="layui-card">
                <div class="layui-card-header" style="background: gray;">
                    <a href="{% url 'myUtils:shownotification' %}?id={{ data.pk }}">{{ data }}&nbsp;&nbsp;  发布时间:&nbsp; {{ data.update_time }}</a>    
                </div>
                <div class="layui-card-body">
                        {{ data.content | truncatechars:10 }}......  
                </div>
              </div>  
                {% endfor %}  
        </div>
            
    </div>
    </body>
</html>