apps/myUtils/urls.py
from django.urls import path
# from .views import Welcome
from .views import Error, Delete_data, Alert_stu_data, Download, GetClass, ShowNotification, GetColleges, AddStu, AddField, ImportDataToexcel, CreateTable, Search, ShareGetClass, CombinedExcel
app_name = 'myUtils'
urlpatterns = [
    path('', Error.as_view(), name='error'),
    path('/delete_stu_data', Delete_data.as_view(), name="delete_stu_data" ),
    path('/alter', Alert_stu_data.as_view(), name="alter"),
    path('/getClass', GetClass.as_view(), name="getClass"),
    path('/getcolleges', GetColleges.as_view(), name='getcolleges'),
    path('/addstu', AddStu.as_view(), name="addstu"),
    path('/addfield', AddField.as_view(), name="addfield"),
    path('/search', Search.as_view(), name='serch'),
    path('/sharegetclass', ShareGetClass.as_view(), name="sharegetclass"),
    path('/combined', CombinedExcel.as_view(), name="combined"),
    path('/import', ImportDataToexcel.as_view(), name='import'),
    path('/createtable', CreateTable.as_view(), name="createtable"),
    path('/shownotification', ShowNotification.as_view(), name="shownotification"),
    path('/download', Download.as_view(), name="download")

]

apps/stu_table/urls.py
from django.urls import path
from .views import Merge, Anomaly, Replenish, Message_edit, Stu_data_list, ShareLogin, ShareForm
app_name = 'stu_table'
urlpatterns = [
    path('merge', Merge.as_view(), name="merge"),
    path('anomaly', Anomaly.as_view(), name="anomaly" ),
    path('replenish', Replenish.as_view(), name="replenish"),
    path('edit', Message_edit.as_view(), name='edit'),
    path('data_list', Stu_data_list.as_view(), name="stu_data_list"),
    path('shareLogin', ShareLogin.as_view(), name="sharelogin"),
    path('shareform', ShareForm.as_view(), name="shareform"),
 
]

intelligent_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static   # 新加入 
from django.conf import settings             # 新加入 
from .views import Index, Welcome, AdminManagement, RoleManagement, Permiclassify, PermiManagement, \
    Login, PermissionAdd, PermissionDelete, PermissionEdit, RoleDelete, RoleAdd, RoleEdit, LogOut, Register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name="login"),
    path('logout', LogOut.as_view(), name="logout"),
    path('register', Register.as_view(), name="register" ),
    path('index', Index.as_view(), name="index"),
    path('welcome', Welcome.as_view(), name="welcome"),
    path('manage/', include('stu_table.urls')),
    path('adminManagement/', AdminManagement.as_view(), name="management"),
    path('user/', include('user.urls')),
    path('role', RoleManagement.as_view(), name="rolemanagement"),
    path('roledelete', RoleDelete.as_view(), name="roledelete"),
    path('roleadd', RoleAdd.as_view(), name="roleadd"),
    path('roleedit', RoleEdit.as_view(), name='roleedit'),
    path('permiclassify', Permiclassify.as_view(), name='permiclassify'),
    path('permiManagement', PermiManagement.as_view(), name="permiManagement"),
    path('permissionadd', PermissionAdd.as_view(), name='permissionadd'),
    path('permissiondelete', PermissionDelete.as_view(), name='permissiondelete'),
    path('permissionedit', PermissionEdit.as_view(), name="permissionedit"),
    path('error', include('myUtils.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/stu_table/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

# Create your models here.

class Stu_base_message(models.Model):
    sno = models.CharField(verbose_name="学号", max_length=50, primary_key=True)
    sname = models.CharField(verbose_name="姓名", max_length=20)
    choice_list = [('男', '男'),
                   ('女', '女')]
    sex = models.CharField(verbose_name="性别", choices=choice_list, max_length=1)

    stu_class = models.ForeignKey('Stu_class', verbose_name="班级", on_delete=models.SET_NULL, null=True, blank=True )

    class Meta:
        verbose_name_plural = "学生信息"
        ordering = ['sno']
    
    def __str__(self):
        return "%s" %self.sno


class Stu_class(models.Model):
    class_name = models.CharField(verbose_name="班级", max_length=50)
    # 学院
    coolege_name = models.ForeignKey('Coolege', verbose_name="学院", on_delete=models.CASCADE, related_name="class_name")
    add_time = models.DateField(verbose_name="添加时间", auto_now_add=True)
    class Meta:
        verbose_name_plural = "班级"
    
    def __str__(self):
        return "%s"%self.class_name


class Coolege(models.Model):    
    coolege_name = models.CharField(verbose_name="学院", max_length=50)
    add_time = models.DateField(verbose_name="添加时间", auto_now_add=True, )
    class Meta:
        verbose_name_plural = "学院"
    
    def __str__(self):
        return "%s"%self.coolege_name

class Transition(models.Model):
    zh_name = models.CharField(verbose_name="中文名", max_length=100, primary_key=True)
    eng_name = models.CharField(verbose_name="英文名", max_length=100)

    class Meta:
        verbose_name_plural = "对照表"



class File(models.Model):
    files = models.FileField(upload_to="file_list")

# 用来删除上传的文件
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=File)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.files.delete(False)

apps/stu_table/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.views.generic import View
from django.contrib.auth import login
from myUtils.utils import session_add_permission, aboout_sno_message
import xlrd
from user.models import Monitor, Profile, Teacher
from .models import File, mymodel_delete, Coolege, Stu_class
from .utils import ExcelOperate, search_fields_list, search_zh_fields_list, paginator_utils
from intelligent_form.forms import LoginForm
from stu_table.utils import search_fields_list


# Create your views here.
# 导入表格
class Merge(View):
    def get(self, request):
        return render(request, template_name="html/upload.html", context={})

    def post(self, request):
        data = {'static': 'error'}
        try:
            file_name = request.FILES['file']
            file_path = File.objects.create(files=file_name)
            # 将数据插入到数据库表中
            ex = ExcelOperate()
            
            ex.file_name = "/home/shance/project/intelligent_form/intelligent_form"+file_path.files.url
            ex.mian()
            instance = file_path
            sender = File
            mymodel_delete(sender,instance)
            if ex.error:
                data['static'] = ex.error
                data['data_list'] = ex.query_list 
                data['query_data'] = ex.query_data
                data['title'] = ex.zh_name
            else: 
                data['static'] = 'success'
            
            # print(data['data_list'])
        except  BaseException:
            pass
        
        return JsonResponse(data)

# 异常信息显示
class Anomaly(View):
    def post(self, request):
        # print(request.POST)
        # print(request.POST.get('data_list'))
        context = {}
        context['data_list'] = eval(request.POST.get('data_list'))
        context['static'] = request.POST.get('static')
        context['eng_list'] = eval(request.POST.get('eng_list'))
        context['title'] = eval(request.POST.get('title'))
        # print(type(eval(request.POST.get('data_list'))))
        # print(request.POST.get('static'))
        # 异常信息展示页面
        return render(request, template_name='stu_table/anomaly.html', context=context)
    
    def get(self, request):
        # 异常信息展示页面
        return render(request, template_name='stu_table/anomaly.html', context={})

# 补录数据
class Replenish(View):
    def post(self, request):
        data = {'status': 'error'}
        data_list = eval(request.POST.get('data'))
        query_list = eval(request.POST.get('eng_list'))
        try:
            ex = ExcelOperate()
            ex.eng_name = eval(query_list)[0]
            ex.data_type = eval(query_list)[1]
            for i in data_list:
                ex.row_data = eval(i)
                ex.binding_name_data()
                ex.update_data(1)
            data['status'] = 'success'
            data['count'] = len(data_list)
        except BaseException:
            pass
        
        return JsonResponse(data)
    
    def get(self, request):
        print(request.GET)
        return HttpResponse("yes")

# 信息编辑
class Message_edit(View):
    def get(self, request):
        if str(request.user.user_role.role_name) == "班长":
            colleges = Coolege.objects.filter(pk=Monitor.objects.get(username=request.user).class_name.coolege_name_id)
        elif str(request.user.user_role.role_name) == "老师":
            colleges = Coolege.objects.filter(pk=Teacher.objects.get(username=request.user).coolege_name_id)
            
        else:
            colleges = Coolege.objects.all()
        context = {
            'colleges': colleges,
            'role': str(request.user.user_role),
        }
        return render(request, template_name="html/stu-message-list.html", context=context)

    def post(self, request):
        pass

class Stu_data_list(View):
    def get(self, request):
        data_tuple = ""
        fields_list, cur, conn = search_fields_list()
        field_list_str = str(fields_list).replace('[', "").replace("]", "").replace("'","")
        give_college = request.GET.get('choice_college')
        give_class = request.GET.get('choice_class')
        stu = request.GET.get('stu')
        # 如果身份是 管理员
        if str(request.user.user_role) == '管理员':
            # 如果进行了筛选
            if stu:
                # search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where A.sno='%s' or A.sname='%s'"%(field_list_str, stu, stu)
                search_sentence = "select %s from stu_table_stu_base_message A left join stu_table_stu_class B on A.stu_class_id = B.id left join stu_table_coolege C on B.coolege_name_id = C.id where A.sno='%s' or A.sname='%s'"%(field_list_str, stu, stu)

            else:
                if give_college:
                    if give_class:
                        # if stu:
                        #     search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where A.sno='%s' or A.sname='%s'"%(field_list_str, stu, stu)
                        # else:
                        # search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where B.id=%s"%(field_list_str, give_class)
                        search_sentence = "select %s from stu_table_stu_base_message A left join stu_table_stu_class B on A.stu_class_id = B.id left join stu_table_coolege C on B.coolege_name_id = C.id where B.id=%s"%(field_list_str, give_class)
                        
                    else:
                        # search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where C.id=%s"%(field_list_str, give_college)
                        search_sentence = "select %s from stu_table_stu_base_message A left join stu_table_stu_class B on A.stu_class_id = B.id left join stu_table_coolege C on B.coolege_name_id = C.id where C.id=%s"%(field_list_str, give_college)

                else:
                    # search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id"%(field_list_str)
                    search_sentence = "select %s from stu_table_stu_base_message A left join stu_table_stu_class B on A.stu_class_id = B.id left join stu_table_coolege C on B.coolege_name_id = C.id"%(field_list_str)
            cur.execute(search_sentence)
            data_tuple = cur.fetchall()
        # 如果身份是辅导员
        if str(request.user.user_role) == '老师':
            objs = Teacher.objects.filter(username=request.user)
            if objs:
                obj = objs[0]
                if stu:
                    search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where A.sno = '%s' or A.sname='%s'"%(field_list_str, stu, stu)
                else:
                    if give_class:
                        search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where B.id = '%s'"%(field_list_str, give_class)
                    else:
                        search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where C.id = '%s'"%(field_list_str, obj.coolege_name_id)                
            cur.execute(search_sentence)
            data_tuple = cur.fetchall()
        # 如果身份是班长
        if str(request.user.user_role) == '班长':
            # 获取班长班级 id
            objs = Monitor.objects.filter(username=request.user)
            if objs:
                obj = objs[0]
                if stu:
                    search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where B.id = %s and (A.sno=%s or A.sname=%s)" %(field_list_str, obj.class_name_id, stu,stu);
                else:
                    
                        
                        # class_name_id = obj.class_name_id
                        # 获取字段
                        
                        # 三表联合查询
                    search_sentence = "select %s from stu_table_stu_base_message A inner join stu_table_stu_class B on A.stu_class_id = B.id inner join stu_table_coolege C on B.coolege_name_id = C.id where B.id = %s" %(field_list_str, obj.class_name_id);
            cur.execute(search_sentence)
            data_tuple = cur.fetchall()
                # 获取学生信息表的字段名:
                # cur.excute("select column_name from information_schema.columns where table_name='stu_table_stu_base_message' and table_schema='manage'")
                # search_fields_list()
        
        cur.close()
        conn.close()
        count = len(data_tuple)
        field_names = search_zh_fields_list(fields_list)
        page = request.GET.get('page')
        data_tuple = paginator_utils(data_tuple, page, 50)
        # 获取所有学院
        if str(request.user.user_role.role_name) == "班长":
            colleges = Coolege.objects.filter(pk=Monitor.objects.get(username=request.user).class_name.coolege_name_id)
        elif str(request.user.user_role.role_name) == "老师":
            colleges = Coolege.objects.filter(pk=Teacher.objects.get(username=request.user).coolege_name_id)
            
        else:
            colleges = Coolege.objects.all()
        

apps/stu_table/templates/stu_table/anomaly.html
{% load static %}
<xblock>
    <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon">&#xe62f;</i>确认导入</button>
    <span class="x-right" style="line-height:40px">未导入的异常数据：<span class='num'>{{ data_list | length }}</span>  条</span>
  </xblock>
  <span style="display: none" id="eng_list">{{ eng_list }}</span>
  <table class="layui-table">
    <thead>
      <tr>
        <th>
            <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
        </th>
        {% for field_name in title %}
          <th>{{ field_name }}</th>
        {% endfor %} 
    </thead>
    <tbody>
        {% for item in data_list %}
      <tr>
        <td>
          <div class="layui-unselect layui-form-checkbox" id="yes" lay-skin="primary" data-id="{{ item }}"><i class="layui-icon">&#xe605;</i></div>
        </td>
            {% for j in item %}
              <td>{{ j }}</td>
            {% endfor %}
      </tr>
        {% endfor %}
    </tbody>
  </table>
<script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>

  

apps/stu_table/templates/stu_table/stu_data_list.html
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'stu_table/css/style.css' %}"> 
{% endblock %}
{% block content %}
</body>
    <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除数据</button>
        <button class="layui-btn" onclick="openModak()"><i class="layui-icon"></i>添加学生</button>
        <button class="layui-btn add-field" onclick="addField()"><i class="layui-icon"></i>添加字段</button>
        <button class="layui-btn selectField"><i class="layui-icon"></i>选择字段导出excel</button>
        <button class="layui-btn share"><i class="layui-icon">&#xe641;</i>分享</button>
        <span class="x-right" style="line-height:40px">共有数据：<span class="count">{{ count }}</span> 条</span>
      </xblock>
    <table class="layui-table">
        <thead>
          <tr>
            <th min-width="100px;">
              <div class="layui-unselect header layui-form-checkbox row" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
              <button class="layui-btn import col" style="display: none"><i class="layui-icon">&#xe641;</i>导出</button>
            </th>
            {% for field_name in field_names %}
              
              <th>{{ field_name }}<input name="field" type="checkbox" style="display: none" value="{{ field_name }}" class="col col_checkbox"> </th>
            {% endfor %}
              <th>操作</th>
            </tr>
        </thead>
        <tbody>
          {% for data_tuple in data_tuples %}
          <tr>
            <td>
                <div class="layui-unselect layui-form-checkbox row" lay-skin="primary" data-id={{data_tuple.0}}><i class="layui-icon">&#xe605;</i></div>
            </td>
            {% for data in data_tuple %}
            <td>{{ data }}</td>
            {% endfor %}
            <td class="td-manage">
              <a title="查看" onclick="x_admin_show('编辑', '/error/alter?sno={{  data_tuple.0 }}')" href="javascript:;">
                <i class="layui-icon">&#xe63c;</i>
              </a>
              <a title="删除" onclick="member_del(this,'{{ data_tuple.0 }}')" href="javascript:;">
                <i class="layui-icon">&#xe640;</i>
              </a>
            </td> 
          {% endfor %}
          </tr>
        </tbody>
      </table>
      <div class="page">
        <div>
          {% if data_tuples.has_previous %}
            <a class="prev" href="?page={{ data_tuples.prevoius_page_number }}">&lt;&lt;</a>
          {% endif %}
          {% for page_num in data_tuples.paginator.page_range %}
            {% if page_num == data_tuples.number %}
            <span class="current">{{ page_num }}</span>
            {% else %}
            <!-- <a class="num" href="?page={{ page_num }}">{{ page_num }}</a> -->
            <a class="num" href="javascript:;" onclick="show_list('{{page_num}}')">{{ page_num }}</a>
            {% endif %}
          {% endfor %}
          {% if data_tuples.has_next%}
            <a class="next" href="?page={{ data_tuples.next_page_number }}">&gt;&gt;</a>
          {% endif %}
        </div>
      </div>
    <!-- 弹出层增加 -->
      <div class="add motaikuang" style="display: none;">
        <div class="form-add" style="width: 350px;">
          <form class="layui-form add-stu-form" >
            {% for field_name in field_names %}
              {% if field_name == "学院" %}
                <div class="layui-form-item">
                        <label class="layui-form-label college">{{ field_name }}</label>
                    <div class="layui-input-block">
                        <select class="cooleges" id = "colleges" name="{{ field_name }}" lay-filter="college">
                          <option value="">请选择学院</option>
                          {% for college in  colleges %}
                            <option value="{{ college.pk }}">{{ college }}</option>
                          {% endfor %}
                        </select>
                    </div>
                </div>
              {% else %}
                  {% if field_name == "班级" %}
                    <div class="layui-form-item">
                        <label class="layui-form-label coolege">{{ field_name }}</label>
                      <div class="layui-input-block">
                        <select class="cooleges"id = "class" name="{{ field_name }}" lay-filter="class">
                            <option value="">请选择班级</option>
                        </select>
                      </div>
                    </div>

                  {% else %}
                    <div class="layui-form-item">
                          <label class="layui-form-label">{{ field_name }}</label>
                        <div class="layui-input-block">
                          <input type="text" name="{{ field_name }}" required  lay-verify="required" placeholder="请输入{{ field_name }}" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                  {% endif %}
              {% endif %}
            {% endfor %}
            <div class="bottom" >
                <button type="button"  class="layui-btn layui-btn-sm layui-btn-normal quit">取消</button><button type="button" class="layui-btn layui-btn-sm layui-btn-normal add-save">保存</button>
            </div>
          </form>
        </div>
      </div>
    </body>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
    <script>
      function openModak(){
            layui.use(['layer'],function () {
                var layer = layui.layer,$=layui.$;
                layer.open({
                    type:1,//类型
                    area:['400px','500px'],//定义宽和高
                    title:'查看详细信息',//题目
                    shadeClose:false,//点击遮罩层关闭
                    content: $('.motaikuang'),//打开的内容,
                });
            })
        }
        layui.use('form', function(){
          var form = layui.form; 
          form.render('select');
          form.on('select(college)', function(data){
            var new_value = data.value;
            if(new_value != ""){
               // ajax提交请求
                $.ajax({
                    url: "{% url 'myUtils:getClass' %}",
                    type: "POST",
                    cache: false,
                    data: {'pk': new_value},
                    success: function(data){
                        var optionstring = "";
                        var meta = JSON.parse(data);
                        $.each(meta, function(i, item){
                            optionstring += '<option selected value="'+item.pk+'">'+item.fields.class_name+'</option>';
                        });
                        $("#class").html('<option value=""></option>' + optionstring);
                        form.render('select');
                    },
                });  
              }
            });
        });
        // 增加学生jq
        $('.add-save').click(function(){
          var data = $('.add-stu-form').serialize();
                // 提交数据
                $.post("{% url 'myUtils:addstu' %}",data,function(obj){
                        if(obj.status=='success'){
                          layui.use(['layer'],function () {
                            var layer = layui.layer,$=layui.$;
                            layer.closeAll(); 
                          })
                                // 重新刷新页面
                                $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}");
                                layer.msg('添加成功', {icon: 1});
                            }else if(obj.status=='sno'){
                                layer.msg('添加失败, 学号是必填项', {icon: 5});
                            }else if(obj.status=='sname'){
                                layer.msg('添加失败, 姓名是必填项', {icon: 5});
                            }else if(obj.status=='sex'){
                                layer.msg('添加失败, 性别是必填的', {icon: 5});
                            }else if(obj.status=='该学生已存在'){
                              layer.msg('添加失败, 该学生已存在', {icon: 5});
                            }
                },"json");
        });
        // 添加字段
        function addField(){
          layer.prompt({
            title: '添加字段,并确认',
            title2:"请写中文", formType: 0,
            success: function(layer0){
              layer0.find(".layui-layer-content").prepend('<div style="margin-bottom: 15px;">请写中文</div>')
            }
            }, function( text, index){
              layer.close(index)
              // 第二个
              layer.prompt({
                title: '填写您字段的类型(填数字)，并确认',
                formType: 0, 
                success: function(layer1){
                  layer1.find(".layui-layer-content").prepend('<div style="margin-bottom: 15px;">字符:1, 数字: 2, 日期:3, 布尔: 4</div>')
                }
                }, function(type, index){
                  $.ajax({
                    type: 'POST',
                    url: "{% url 'myUtils:addfield' %}",
                    data: {'text': text, "type": type },
                    success:function(data){
                      console.log(data)
                      if (data.static == "成功"){
                        layer.msg('添加成功', {icon: 1});
                        $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}");
                      }else{
                        layer.msg(''+data.static, {icon: 5});
                      }
                      
                    }
                  });
                  // $.post("{% url 'myUtils:addfield' %}",{'text': text, "type": type }, function(data){
                  //   alert(result)
                  //   if (data.status == "成功"){
                  //     console.log('yes')
                  //     layer.msg('添加成功', {icon: 1});
                  //     $('.about_data_list').load("{% url 'stu_table:stu_data_list' %}");
                  //   }else{
                  //     layer.msg(''+data.status, {icon: 5});
                  //   }
                      
                  // })
              layer.close(index);
              });
            // $.post("{% url 'myUtils:addfield' %}",{'text': text}, function(obj){
            //   console.log(obj)
            // }, 'json')
          });
        }
        // 关闭弹框
        $('.quit').click(function(){
          layui.use(['layer'],function () {
                            var layer = layui.layer,$=layui.$;
                            layer.closeAll(); 
            })
        });
        $('.share').click(function(){
          layer.prompt({
                title: '复值链接',
                id:'sharetext',
                value: 'http://127.0.0.1:8000/manage/shareLogin',
                btn:["复制"],
                yes: function(index){
                  var Url2=$('.layui-layer-input').val();
                  var oInput = document.createElement("input");
                  oInput.value = Url2;
                  document.body.appendChild(oInput);
                  oInput.select(); // 选择对象
                  document.execCommand("Copy"); // 执行浏览器复制命令
                  oInput.className = "oInput";
                  oInput.style.display = "none";
                  layer.msg('复制成功',{icon:1,time:1000});
                },
                success: function(layer0, index){
                  $('#sharetext input').attr("readOnly", "readOnly");
                },
                }, function(type, index){
                });
        })
    $('.selectField').click(function(){
      var col_checkbox = $('.col')
      var row_checkbox = $('.row')
      if(col_checkbox.css('display') == 'none'){
        col_checkbox.show();
        row_checkbox.hide();
        $('.selectField').text('取消')
      }else{
        col_checkbox.hide();
        row_checkbox.show();
        $('.selectField').text('选择字段导出excel')
      }
    });
    $('.import').click(function(){
      var arry = []
      $('input[name="field"]:checked').each(function(index, element) {
                //追加到数组中
                arry.push($(this).val());
            });
            var csrf=$('input[name="csrfmiddlewaretoken"]').val();
         const req = new XMLHttpRequest();
         req.open('POST', "{% url 'myUtils:import' %}", true);
         req.responseType = 'blob';
         req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded'); //设置请求头
         req.send('field='+JSON.stringify(arry)+"&&csrfmiddlewaretoken="+csrf); //输入参数
         req.onload = function() {
             const data = req.response;
             const a = document.createElement('a');
             const blob = new Blob([data]);
             const blobUrl = window.URL.createObjectURL(blob);
             download(blobUrl) ;
         };
    });
    function download(blobUrl) {
    var city = $("input[name='city']").val();
    const a = document.createElement('a');
    a.style.display = 'none';
    a.download = '学生表.xls';
    a.href = blobUrl;
    a.click();
    
  }
    </script>
{% endblock %}