apps/myUtils/urls.py
from django.urls import path
# from .views import Welcome
from .views import Error, Delete_data, Alert_stu_data, Download, GetClass, ShowNotification, GetColleges, AddStu, AddField, ImportDataToexcel, CreateTable, Search, ShareGetClass, CombinedExcel
app_name = 'myUtils'
urlpatterns = [
    path('', Error.as_view(), name='error'),
    path('/delete_stu_data', Delete_data.as_view(), name="delete_stu_data" ),
    path('/alter', Alert_stu_data.as_view(), name="alter"),
    path('/getClass', GetClass.as_view(), name="getClass"),
    path('/getcolleges', GetColleges.as_view(), name='getcolleges'),
    path('/addstu', AddStu.as_view(), name="addstu"),
    path('/addfield', AddField.as_view(), name="addfield"),
    path('/search', Search.as_view(), name='serch'),
    path('/sharegetclass', ShareGetClass.as_view(), name="sharegetclass"),
    path('/combined', CombinedExcel.as_view(), name="combined"),
    path('/import', ImportDataToexcel.as_view(), name='import'),
    path('/createtable', CreateTable.as_view(), name="createtable"),
    path('/shownotification', ShowNotification.as_view(), name="shownotification"),
    path('/download', Download.as_view(), name="download")

]

apps/stu_table/urls.py
from django.urls import path
from .views import Merge, Anomaly, Replenish, Message_edit, Stu_data_list, ShareLogin, ShareForm
app_name = 'stu_table'
urlpatterns = [
    path('merge', Merge.as_view(), name="merge"),
    path('anomaly', Anomaly.as_view(), name="anomaly" ),
    path('replenish', Replenish.as_view(), name="replenish"),
    path('edit', Message_edit.as_view(), name='edit'),
    path('data_list', Stu_data_list.as_view(), name="stu_data_list"),
    path('shareLogin', ShareLogin.as_view(), name="sharelogin"),
    path('shareform', ShareForm.as_view(), name="shareform"),
 
]

apps/user/urls.py
from django.urls import path
from .views import UserList, ChangePassword, AddUser, DeleteUser, PersonalDetails

app_name = 'user'
urlpatterns = [
    path('userlist', UserList.as_view(), name='userlist'),
    path('changepassword', ChangePassword.as_view(), name='changepassword'),
    path('adduser', AddUser.as_view(), name="adduser"),
    path('deleteuser', DeleteUser.as_view(), name='deleteuser'),
    path('personaldetails', PersonalDetails.as_view(), name="personaldetails")
]

intelligent_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static   # 新加入 
from django.conf import settings             # 新加入 
from .views import Index, Welcome, AdminManagement, RoleManagement, Permiclassify, PermiManagement, \
    Login, PermissionAdd, PermissionDelete, PermissionEdit, RoleDelete, RoleAdd, RoleEdit, LogOut, Register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name="login"),
    path('logout', LogOut.as_view(), name="logout"),
    path('register', Register.as_view(), name="register" ),
    path('index', Index.as_view(), name="index"),
    path('welcome', Welcome.as_view(), name="welcome"),
    path('manage/', include('stu_table.urls')),
    path('adminManagement/', AdminManagement.as_view(), name="management"),
    path('user/', include('user.urls')),
    path('role', RoleManagement.as_view(), name="rolemanagement"),
    path('roledelete', RoleDelete.as_view(), name="roledelete"),
    path('roleadd', RoleAdd.as_view(), name="roleadd"),
    path('roleedit', RoleEdit.as_view(), name='roleedit'),
    path('permiclassify', Permiclassify.as_view(), name='permiclassify'),
    path('permiManagement', PermiManagement.as_view(), name="permiManagement"),
    path('permissionadd', PermissionAdd.as_view(), name='permissionadd'),
    path('permissiondelete', PermissionDelete.as_view(), name='permissiondelete'),
    path('permissionedit', PermissionEdit.as_view(), name="permissionedit"),
    path('error', include('myUtils.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    {% block link %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
</head>
    {% block content %}{% endblock %}
    {% block script %}{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

    <!-- 顶部开始 -->
    {% block title%} 主页 {% endblock %}
    {% block content %}
    <body>
        <div class="container">
            <div class="logo"><a href="{% url 'index' %}"><img style="height: 30px; width: 30px;" class="logo" src="{% static 'images/logo.png' %}" alt=""> {{ request.user.name }}</a></div>
            <div class="left_open">
                <i title="展开左侧栏" class="iconfont">&#xe699;</i>
            </div>
            <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">admin</a>
                <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a onClick="x_admin_show('个人信息','/user/personaldetails',600,400)">个人信息</a></dd>
                <dd><a onClick="x_admin_show('个人信息','/user/changepassword?pk={{ request.user.pk }}',600,400)">修改密码</a></dd>
                <dd><a href="{% url 'logout' %}"">退出</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index"><a href="{% url 'index' %}">前台首页</a></li>
            </ul>
            
        </div>
        <!-- 顶部结束 -->
        <!-- 中部开始 -->
        <!-- 左侧菜单开始 -->
        <div class="left-nav">
        <div id="side-nav">
            <ul id="nav">
                <li >
                    <a href="javascript:;">
                        <i class="iconfont">&#xe6eb;</i>
                        <cite>主页</cite>
                        <i class="iconfont nav_right">&#xe6a7;</i>
                    </a>
                    <ul class="sub-menu">
                        <li><a _href="{% url 'welcome' %}"><i class="iconfont">&#xe6a7;</i><cite>控制台</cite></a></li >
                    </ul>
                </li>
                <li>
                    <a href="javascript:;"><i class="iconfont">&#xe6f6;</i><cite>数据管理</cite><i class="iconfont nav_right">&#xe6a7;</i></a>
                    <ul class="sub-menu">
                        <li><a _href="{% url 'stu_table:merge' %}"><i class="iconfont">&#xe6a7;</i><cite>导入表格</cite></a></li>
                        <li><a _href="{% url 'stu_table:edit' %}"><i class="iconfont">&#xe6a7;</i><cite>信息编辑</cite></a></li>
                            <!-- 信息编辑页面 -->
                    </ul>
                </li>
                <li >
                    <a href="javascript:;">
                        <i class="iconfont">&#xe6b4;</i>
                        <cite>工具</cite>
                        <i class="iconfont nav_right">&#xe6a7;</i>
                    </a>
                    <ul class="sub-menu">
                        <!-- <li><a _href="{% url 'myUtils:combined' %}"><i class="iconfont">&#xe6a7;</i><cite>合并表格</cite></a></li> -->
                        <li><a _href="{% url 'myUtils:createtable' %}"><i class="iconfont">&#xe6a7;</i><cite>生成表格</cite></a></li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="iconfont">&#xe726;</i>
                        <cite>管理员管理</cite>
                        <i class="iconfont nav_right">&#xe6a7;</i>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a _href="{% url 'user:userlist' %}">
                                <i class="iconfont">&#xe6a7;</i>
                                <cite>用户列表</cite>
                            </a>
                        </li >
                        <li>
                            <a _href="{% url 'rolemanagement' %}">
                                <i class="iconfont">&#xe6a7;</i>
                                <cite>角色管理</cite>
                            </a>
                        </li >
                        <!-- <li>
                            <a _href="{% url 'permiclassify' %}">
                                <i class="iconfont">&#xe6a7;</i>
                                <cite>权限分类</cite>
                            </a>
                        </li > -->
                        <li>
                            <a _href="{% url 'permiManagement' %}">
                                <i class="iconfont">&#xe6a7;</i>
                                <cite>权限管理</cite>
                            </a>
                        </li >
                    </ul>
                </li>            
        </div>
        </div>
        <!-- <div class="x-slide_left"></div> -->
        <!-- 左侧菜单结束 -->
        <!-- 右侧主体开始 -->
        <div class="page-content">
            <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
            <ul class="layui-tab-title">
                <li class="home"><i class="layui-icon">&#xe68e;</i>我的桌面</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <iframe src="{% url 'welcome' %}" frameborder="0" scrolling="yes" class="x-iframe"></iframe>
                </div>
            </div>
            </div>
        </div>
        <div class="page-content-bg"></div>
        <!-- 右侧主体结束 -->
        <!-- 中部结束 -->
        <!-- 底部开始 -->
        <!--<div class="footer">
            <div class="copyright">Copyright ©2019 L-admin v2.3 All Rights Reserved</div>  
        </div>-->
        <!-- 底部结束 -->
    </body>
{% endblock %}

templates/login.html

<!-- <!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>带摇晃特效的扁平风格登录注册表单界面</title>
<link rel="stylesheet" type="text/css" href="css/login.css"> -->
<!-- </head> -->
{% extends 'base.html' %}
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<body>
<div id="wrapper" class="login-page">
<div id="login_form" class="form">
<form class="register-form">
	<h2>创建用户</h2>
<input type="text" placeholder="用户名" value="admin" id="r_user_name" />
<input type="password" placeholder="密码" id="r_password" />
<input type="text" placeholder="电子邮件" id="r_emial" />
<button id="create">创建账户</button>
<p class="message">已经有了一个账户? <a href="#">立刻登录</a></p>
</form>
<form method="POST" class="login-form" novalidate>
	<h2>管理登录</h2>
	{% csrf_token %}
	{% for field in loginForm %}
		{{ field }}
	{% endfor %}
<button id="login">登　录</button>
<p class="message">还没有账户? <a href="#">立刻创建</a></p>
</form>
</div>
</div>
</body>
{% endblock %}
<!-- <script src="js/jquery.min.js"></script>
 -->
 {% block script %}
<script type="text/javascript">
	$('#login').click(function(){
		var name=$("#user_name").val();
	 	var password=$("#password").val();
		if (name == ""){
			layer.msg('用户名不能为空', {icon: 5});
			return false;
		}else if(password == ""){
			layer.msg('密码不能为空', {icon: 5});
			return false;
		}else{
			$.ajax({
			url: "{% url 'login' %}",
			type: "POST",
			data: {'username': name, 'password': password},
			cache: false,
			async: false,
			success: function(data){
				if(data['errormessage']!=null){
					  $("#login_form").removeClass('shake_effect');  
					  setTimeout(function()
					  {
					   $("#login_form").addClass('shake_effect')
					  },1);  
					layer.msg('用户名或密码错误', {icon: 5});
				}
				if(data['status'] == '登录成功'){
						location.href = '{% url "index" %}'
					}
			},
			error: function(xhr){
				layer.msg('登录失败', {icon: 5});
			}
			});
			return false;
		}
		
	});
	function check_register(){
		var name = $("#r_user_name").val();
		var pass = $("#r_password").val();
		var email = $("r_email").val();
		if(name!="" && pass=="" && email != "")
		 {
		  alert("注册成功！");
		  $("#user_name").val("");
		  $("#password").val("");
		 }
		 else
		 {
		  $("#login_form").removeClass('shake_effect');  
		  setTimeout(function()
		  {
		   $("#login_form").addClass('shake_effect')
		  },1);  
		 }
	}
	$(function(){
		$("#create").click(function(){
			check_register();
			return false;
		})
		// $("#login").click(function(){
		// 	check_login();
		// 	return false;
		// })
		$('.message a').click(function () {
		    $('form').animate({
		        height: 'toggle',
		        opacity: 'toggle'
		    }, 'slow');
		});
	})
	</script>
{% endblock %}

templates/permission_edit.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'stu_table/css/admin-rule.css' %}">
{% endblock %}
{% block content %}
<body>
    <div class="permission">
        <form class="edit-permission">
            <input type="hidden" name="pk" value="{{ obj.pk }}">
            <div class="layui-form-item">
                <label class="layui-form-label">权限名称</label>
                <div class="layui-input-block">
                  <input type="text" name="rule_name" required  value="{{ obj.permission_name }}" lay-verify="required" placeholder="请输入权限名称" autocomplete="off" class="layui-input">
                </div>
              </div>
              <div class="layui-form-item">
                <label class="layui-form-label">权限路由</label>
                <div class="layui-input-block">
                  <input type="text" name="rule_url" required  value="{{ obj.url }}" lay-verify="required" placeholder="请输入权限名称" autocomplete="off" class="layui-input">
                </div>
              </div>
              <div class="layui-form-item layui-form-text">
                <label class="layui-form-label">权限描述</label>
                <div class="layui-input-block">
                  <textarea name="desc" placeholder="请写权限描述""  class="layui-textarea">{{ obj.permission_description }}</textarea>
                </div>
              </div>
              <div class="bottom" >
                <button type="button"  class="layui-btn layui-btn-sm layui-btn-normal quit">取消</button><button type="button" class="layui-btn layui-btn-sm layui-btn-normal edit-rule-save">保存</button>
              </div>
        </form>
    </div>
</body>
{% endblock %}
{% block script %}
    <script>
        $('.edit-rule-save').click(function(){
            var data = $('.edit-permission').serialize()
            $.post('{% url "permissionedit" %}', data, function(){
                var index=parent.layer.getFrameIndex(window.name); //获取当前窗口的name
                parent.layer.close(index);
                parent.location.reload();
            })
        });
        $('.quit').click(function(){
            var index=parent.layer.getFrameIndex(window.name); //获取当前窗口的name
            parent.layer.close(index);
      });
    </script>
{% endblock %}

templates/personaldetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form class="layui-form"  novalidate>
    {% for field in personalForm %}
    <div class="layui-form-item">
        <label class="layui-form-label">用户名</label>
        <div class="layui-input-block">
            <input type="text" name="username" required  lay-verify="required" readonly="true" placeholder="" value="{{ field.username }}" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">姓名</label>
        <div class="layui-input-block">
            <input type="text" name="name" required  value="{{ field.name }}" lay-verify="required" placeholder="请输入姓名" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">电话</label>
        <div class="layui-input-block">
            <input type="text" name="phone" required  value="{{ field.phone }}" lay-verify="required" placeholder="请输入电话" autocomplete="off" class="layui-input phone">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">邮箱</label>
        <div class="layui-input-block">
            <input type="text" name="email" required  value="{{ field.email }}" lay-verify="required" placeholder="请输入邮箱" autocomplete="off" class="layui-input email">
        </div>
    </div>
    {% endfor %}
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
        </div>
    </div>
</form>
{% endblock %}
{% block script %}
<script>
    //Demo
    layui.use('form', function(){
        var form = layui.form;
        //监听提交
        form.on('submit(formDemo)', function(data){
            var myreg=/^[1][3,4,5,7,8][0-9]{9}$/;
            var myreg2 = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
            var phone = $('.phone').val();
            // 验证邮箱和电话
            var email = $('.email').val();
            if(myreg.test(phone)){
                if(myreg2.test(email)){
                    save(data)
                }else{
                    layer.msg("请填写正确邮箱",{icon: 5,time:1000, shift: 6},);
                }
            }else{
                layer.msg("请填写正确电话",{icon: 5,time:1000, shift: 6},);
            }
        return false;
        });
    });

    function save(data){
        $.ajax({
                url: "/user/personaldetails",
                type: 'post',
                data: data.field,
                cache: false,
                success: function(data){
                    if(data.status == "yes"){
                        layer.msg("保存成功",{icon: 1,time:1000, shift: 6},);
                    }
                },
                error: function(xhr){
                    console.log(xhr);
                }
            })
    }
</script>
{% endblock %}

templates/share_login.html

<!-- <!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>带摇晃特效的扁平风格登录注册表单界面</title>
<link rel="stylesheet" type="text/css" href="css/login.css"> -->
<!-- </head> -->
{% extends 'base.html' %}
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<body>
<div id="wrapper" class="login-page">
<div id="login_form" class="form">
<form class="register-form layui-form">
	<h2>创建用户</h2>
<input type="text" placeholder="输入学号作为用户名" id="r_user_name" />
<input type="text" placeholder="输入姓名" id="r_name" />
<input type="password" placeholder="密码" id="r_password" required lay-verify="required" />
<input type="password" placeholder="确认密码" id="r_passwordAgain" lay-verify="required" />
<input type="text" placeholder="电子邮件" id="r_email"  lay-verify="required"/>

<button id="create">创建账户</button>
<p class="message">已经有了一个账户? <a href="#">立刻登录</a></p>
</form>
<form method="POST" class="login-form" novalidate>
	<h2>管理登录</h2>
	{% csrf_token %}
	{% for field in loginForm %}
		{{ field }}
	{% endfor %}
<button id="login">登　录</button>
<p class="message">还没有账户? <a href="#">立刻创建</a></p>
</form>
</div>
</div>
</body>
{% endblock %}
<!-- <script src="js/jquery.min.js"></script>
 -->
 {% block script %}
<script type="text/javascript">
	$('#login').click(function(){
		var name=$("#user_name").val();
	 	var password=$("#password").val();
		if (name == ""){
			layer.msg('用户名不能为空', {icon: 5});
			return false;
		}else if(password == ""){
			layer.msg('密码不能为空', {icon: 5});
			return false;
		}else{
			$.ajax({
			url: "{% url 'stu_table:sharelogin' %}",
			type: "POST",
			data: {'username': name, 'password': password},
			cache: false,
			async: false,
			success: function(data){
				if(data['errormessage']!=null){
					  $("#login_form").removeClass('shake_effect');  
					  setTimeout(function()
					  {
					   $("#login_form").addClass('shake_effect')
					  },1);  
					layer.msg('用户名或密码错误', {icon: 5});
				}
				if(data['status'] == '登录成功'){
						location.href = '/manage/shareform?sno='+data.username

					}
			},
			error: function(xhr){
				layer.msg('登录失败', {icon: 5});
			}
			});
			return false;
		}
		
	});
	function check_register(){
		var username = $("#r_user_name").val();
		var pass = $("#r_password").val();
		var name = $("#r_name").val();
		var passAgain = $("#r_passwordAgain").val();
		var email = $("#r_email").val();
		var myreg2 = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
		if(username == ""){
			layer.msg('用户名不能为空', {icon: 5});
		}else if(name == ""){
			layer.msg('名字不能为空', {icon: 5});
		}else if(pass=="" || passAgain==""){
			layer.msg('密码不能为空', {icon: 5});
		}else if(email == ""){
			layer.msg('邮箱不能为空', {icon: 5});
		}else if(myreg2.test(email)){
			if(pass == passAgain){
				if(pass.length >= 6){
					$.post('/register',{'username': username, 'password': pass, "email": email, 'name': name}, function(data){
						if(data.status == "注册成功"){
							location.href = '/manage/shareform?sno='+data.username
						}else{
							layer.msg(data.status, {icon: 5});
						}
					} )
				}else{
					layer.msg('密码必须6位以上', {icon: 5});
				}
			}else{
				layer.msg('两次密码不一致', {icon: 5});
			}

		}else{
			layer.msg('邮箱格式不正确', {icon: 5});
		}
		// if(name!="" && pass=="" && email != "")
		//  {
		//   alert("注册成功！");
		//   $("#user_name").val("");
		//   $("#password").val("");
		//  }
		//  else
		//  {
		//   $("#login_form").removeClass('shake_effect');  
		//   setTimeout(function()
		//   {
		//    $("#login_form").addClass('shake_effect')
		//   },1);  
		//  }
	}
	$(function(){
		$("#create").click(function(){
			check_register();
			return false;
		})
		$("#login").click(function(){
			check_login();
			return false;
		})
		$('.message a').click(function () {
		    $('form').animate({
		        height: 'toggle',
		        opacity: 'toggle'
		    }, 'slow');
		});
	})
	</script>
{% endblock %}

templates/shareform.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 修改学生信息 {% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static 'stu_table/css/style.css' %}"> 
{% endblock %}
{% block content %}
<body>
    <div class="form-content">
        <form class="layui-form stu_message">
                <div class="layui-form-item">
                    {% for field_data in field_datas %}
                        {% if field_data.0 == "学院" %}
                            <div class="layui-form-item">
                                    <label class="layui-form-label coolege">{{ field_data.0 }}</label>
                                    <div class="layui-input-block">
                                        <select class="cooleges"id = "cooleges" name="{{ field_data.0 }}" lay-filter="coolege">
                                                <option value="">请选择</option>
                                                
                                            {% for coolege in cooleges %}
                                                <option value="{{ coolege.id }}"  {% if coolege == this_coolege %} selected {% endif %}>{{ coolege }}</option>
                                            {% endfor %}
                                            
                                        </select>
                                    </div>
                                </div>
                            {% else %}
                                {% if field_data.0 == "班级" %}
                                    <div class="layui-form-item">
                                            <label class="layui-form-label class_name">{{ field_data.0 }}</label>
                                            <div class="layui-input-block">
                                                <select name="{{ field_data.0 }}" id = "class_names" lay-verify="required">
                                                    {% for class_name in class_names %} 
                                                        <option value="{{ class_name.id }}" {% if class_name == this_class %} selected {% endif %}>{{ class_name }}</option>  
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    {% else %}
                                        {% if field_data.0 == "学号" %}
                                        <label class="layui-form-label">{{ field_data.0 }}</label>
                                        <div class="layui-input-block">
                                            <input type="text" name="{{ field_data.0 }}" required  lay-verify="required" placeholder="请输入{{ field_data.0 }}" autocomplete="off" class="layui-input" value="{{ request.user.username}}" readonly="readonly">
                                        </div>
                                        {% else %}
                                        <label class="layui-form-label">{{ field_data.0 }}</label>
                                        <div class="layui-input-block">
                                            <input type="text" name="{{ field_data.0 }}" required  lay-verify="required" placeholder="请输入{{ field_data.0 }}" autocomplete="off" class="layui-input" value="{{ field_data.1 }}">
                                        </div>
                                        {% endif %}
                                {% endif %}
                        {% endif %}  
                    {% endfor %}
                    <div class="bottom" >
                        <button type="button"  class="layui-btn layui-btn-sm layui-btn-normal quit">取消</button><button onclick="save()" type="button" class="layui-btn layui-btn-sm layui-btn-normal save">保存</button>
                    </div>
        </form>
    </div>
</bpdy>
{% endblock %}
{% block script %}
<script>
    layui.use('form', function(){
        var form = layui.form; 
        form.render('select');
        form.on('select(coolege)', function(data){
            var new_value = data.value;
            if (new_value != ""){
                // ajax提交请求
                $.ajax({
                    url: "{% url 'myUtils:sharegetclass' %}",
                    type: "POST",
                    cache: false,
                    data: {'pk': new_value},
                    success: function(data){
                        var optionstring = "";
                        var meta = JSON.parse(data);
                        $.each(meta, function(i, item){
                            optionstring += '<option value="'+item.pk+'">'+item.fields.class_name+'</option>';
                        });
                        $("#class_names").html('<option value="">请选择班级</option>' + optionstring);
                        form.render('select');
                    },
                });   
            }
        });
    });
        // 保存数据
        function save(){
                var data = $('.stu_message').serialize();
                // 提交数据
                $.post("{% url 'myUtils:alter' %}",data,function(obj){
                        if(obj.status=='成功'){
                                layer.msg('修改成功', {icon: 1});
                            }else if(obj.status=='失败'){
                                layer.msg('修改失败', {icon: 5});
                            }else if(obj.status=='数据没有改动'){
                                layer.msg('信息并未改变', {icon: 1});
                            }
                },"json");
            };
        $('.quit').click(function(){
            var index=parent.layer.getFrameIndex(window.name); //获取当前窗口的name
            parent.layer.close(index);	
        });
       
</script>
{% endblock %}